DROP TABLE IF EXISTS driver;
CREATE TABLE driver(
    driverId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    firstName VARCHAR(20) NOT NULL,
    lastName VARCHAR(20) NOT NULL,
    driverLicence VARCHAR(9) NOT NULL UNIQUE
    workDate TIMESTAMP NOT NULL
);
DROP TABLE IF EXISTS car;
CREATE TABLE car (
    carId INT NOT NULL AUTO_INCREMENT,
    nameCar VARCHAR(20) INT NOT NULL,
    typeCar VARCHAR(20) NOT NULL,
    driverId INT NOT NULL,
  );